#!/bin/sh
set -e

case "$1" in
    remove|purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        if [ -d /run/systemd/system ]; then
            systemctl --system daemon-reload >/dev/null || true
        fi
    ;;

    *)
        echo "postrm chamado com argumento desconhecido: $1" >&2
        exit 1
    ;;
esac

exit 0
